version: '3'
services:
  postgresdb:
    image: postgres:alpine
    volumes:
      - ./data:/var/lib/postgresql/
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"